VShop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
urlpatterns = [
       path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('session/add-product/', views.SessionAddProductView.as_view(), name='session-add-product'),
]

product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'product'

urlpatterns = [
    path('grid/', views.ProductGridView.as_view(), name='product-grid'),
    path('list/', views.ProductListView.as_view(), name='product-list'),
    path(r'detail/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
]

product/models.py
from django.db import models
from accounts.models import User
from decimal import Decimal

class ProductStatusType(models.IntegerChoices):
    active = 1, ('فعال')
    inactive = 2, ('غیر فعال')

class ProductCategory(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.title

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='products')
    category = models.ManyToManyField('ProductCategory')
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True)
    image = models.ImageField(upload_to='products/images/')
    description = models.TextField()
    stock = models.PositiveIntegerField(default=0)
    status = models.IntegerField(choices=ProductStatusType.choices, default=ProductStatusType.active)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount_percent = models.PositiveSmallIntegerField(default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def get_raw_price(self):
        return int(self.price)

    def get_real_price(self):
        discount_amount = self.price * Decimal(self.discount_percent / 100)
        discounted_amount = self.price - discount_amount
        return int(discounted_amount)

    class Meta:
        db_table = 'product'

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='extra_images')
    image = models.ImageField(upload_to='products/extra-images/')

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_image'

product/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import DetailView, ListView
from django.core.exceptions import FieldError

from product.models import *


class ProductGridView(ListView):
    template_name = 'product/product-grid.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 9

    def get_paginate_by(self, queryset):
        page_size = self.request.GET.get('page_size', self.paginate_by)
        try:
            if int(page_size) > 50:
                page_size = 50
        except ValueError:
            page_size = self.paginate_by

        return page_size


    def get_queryset(self, **kwargs):
        query = super().get_queryset()
        query = query.filter(status=ProductStatusType.active).all().prefetch_related('category')

        # Query Search
        q_search = self.request.GET.get('q')
        if q_search:
            query = query.filter(title__icontains=q_search)

        # Min Price
        min_price = self.request.GET.get('min_price')
        if min_price:
            query = query.filter(price__gte=min_price)

        # Max Price
        max_price = self.request.GET.get('max_price')
        if max_price:
            query = query.filter(price__lte=max_price)

        # Category
        category_id = self.request.GET.get('category_id')
        if category_id:
            query = query.filter(category__id=category_id)

        order_by = self.request.GET.get('order_by')
        if order_by:
            try:
                query = query.order_by(order_by)
            except FieldError:
                pass


        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_items'] = self.get_queryset().count()
        context['categories'] = ProductCategory.objects.all()

        return context

class ProductListView(View):
    def get(self, request):
        return render(request, 'product/product-list.html')


class ProductDetailView(DetailView):
    template_name = 'product/product-detail.html'
    queryset = Product.objects.filter(status=ProductStatusType.active).all()
    context_object_name = 'product'

product/templates/product/includes/latest_product.html
<!-- Card Grid -->
<div class="container content-space-2 content-space-lg-3">
    <!-- Title -->
    <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
        <h2>جدید ترین ها</h2>
    </div>
    <!-- End Title -->

    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mb-3">
        {% include 'product/includes/product_list.html' with products=latest_products %}
    </div>
    <!-- End Row -->

    <div class="text-center">
        <a class="btn btn-outline-primary btn-transition rounded-pill" href="{% url 'product:product-grid' %}">مشاهده تمامی محصولات</a>
    </div>
</div>
<!-- End Card Grid -->

product/templates/product/includes/product_list.html
{% load static %}
{% load poll_extras %}
{% load thumbnail %}

{% for product in products %}
    <div class="col mb-4">
        <!-- Card -->
        <div class="card card-bordered shadow-none text-center h-100">
            <div class="card-pinned">
                {% thumbnail product.image "300x200" crop="center" as img %}
                    <img src="{{ img.url }}" class="card-img-top" alt="{{ product.title }}">
                {% endthumbnail %}

                {% if product.discount_percent %}
                    <div class="card-pinned-top-start">
                        <span class="badge bg-danger rounded-pill">{{ product.discount_percent }}% تخفیف</span>
                    </div>
                {% endif %} 

                <div class="card-pinned-top-end">
                    <button type="button"
                            class="btn btn-outline-secondary btn-xs btn-icon rounded-circle"
                            data-bs-toggle="tooltip" data-bs-placement="top"
                            title="افزودن به علایق">
                        <i class="bi-heart"></i>
                    </button>
                </div>
            </div>

            <div class="card-body">
                <div class="mb-2">
                    {% for category in product.category.all %}
                        <a class="link-sm link-secondary" href="#"> {{ category.title }} </a>
                        {% if not forloop.last %}
                            ,
                        {% endif %}
                    {% endfor %}
                </div>

                <h4 class="card-title">
                    <a class="text-dark" href="{% url 'product:product-detail' pk=product.pk %}">{{ product.title }}</a>
                </h4>
                <!-- Price -->
                {% if product.discount_percent %}
                    <p class="card-text text-dark fs-4">
                        <span class="formatted-price">{{ product.get_real_price|three_digits_currency }}</span>
                        <span class="text-body me-1 fs-6 formatted-price text-decoration-line-through">{{ product.get_raw_price|three_digits_currency }}</span>
                    </p>
                {% else %}
                    <p class="card-text text-dark fs-4 formatted-price"> {{ product.get_raw_price|three_digits_currency }}</p>
                {% endif %}
                <!-- End Price -->
                
            </div>

            <div class="card-footer pt-0">
                <!-- Rating -->
                <a class="d-inline-flex align-items-center mb-3" href="#">
                    <div class="d-flex gap-1 ms-2">
                        <img src="{% static '/svg/illustrations/star-muted.svg' %}"
                             alt="Review rating" width="16">
                        <img src="{% static '/svg/illustrations/star-muted.svg' %}"
                             alt="Review rating" width="16">
                        <img src="{% static '/svg/illustrations/star-muted.svg' %}"
                             alt="Review rating" width="16">
                        <img src="{% static '/svg/illustrations/star-muted.svg' %}"
                             alt="Review rating" width="16">
                        <img src="{% static '/svg/illustrations/star-muted.svg' %}"
                             alt="Review rating" width="16">
                    </div>
                    <span class="small">0</span>
                </a>
                <!-- End Rating -->

                <button type="button" onclick="addToCart({{ product.id }})" class="btn btn-outline-primary btn-sm btn-transition rounded-pill">
                    افزودن به سبد خرید
                </button>
            </div>
        </div>
        <!-- End Card -->
    </div>
    <!-- End Col -->
{% empty %}
    <div class="row text-center w-100 py-5">
        <p class="text-center">هیچ کالایی برای نمایش وجود ندارد</p>
    </div>
{% endfor %}

product/templates/product/includes/similar_product.html
<!-- Card Grid -->
<div class="container content-space-2 content-space-lg-3">
    <!-- Title -->
    <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
        <h2>محصولات مرتبط</h2>
    </div>
    <!-- End Title -->

    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        {% include 'product/includes/product_list.html' with products=similar_products %}
    </div>
    <!-- End Row -->
</div>
<!-- End Card Grid -->